#!/bin/bash
# Install saas-mirror as a macOS launchd service.
#
# What this does:
#   1. Generates a launchd plist with correct absolute paths
#   2. Symlinks it into ~/Library/LaunchAgents/
#   3. Loads the service via launchctl
#
# Usage:
#   scheduling/setup.sh           # install and load
#   scheduling/setup.sh uninstall # unload and remove

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MIRROR_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PLIST_NAME="com.saas-mirror.sync"
PLIST_FILE="$SCRIPT_DIR/$PLIST_NAME.plist"
AGENTS_DIR="$HOME/Library/LaunchAgents"
LINK_PATH="$AGENTS_DIR/$PLIST_NAME.plist"

# --- Uninstall ---
if [ "${1:-}" = "uninstall" ]; then
    echo "Uninstalling saas-mirror launchd service..."
    if launchctl list "$PLIST_NAME" &>/dev/null; then
        launchctl unload "$LINK_PATH" 2>/dev/null || true
        echo "  Unloaded $PLIST_NAME"
    fi
    rm -f "$LINK_PATH"
    echo "  Removed $LINK_PATH"
    echo "Done. The plist at $PLIST_FILE is still on disk."
    exit 0
fi

# --- Pre-flight checks ---
echo "Setting up saas-mirror launchd service..."
echo "  Repo: $MIRROR_DIR"
echo ""

if [ ! -f "$MIRROR_DIR/.env.local" ]; then
    echo "WARNING: .env.local not found at $MIRROR_DIR/.env.local"
    echo "  Copy .env.example to .env.local and configure your API keys before the first sync."
    echo ""
fi

for cmd in node yarn; do
    if command -v "$cmd" &>/dev/null; then
        echo "  $cmd: $(command -v "$cmd") ($(command "$cmd" --version 2>/dev/null || echo 'unknown version'))"
    else
        echo "  WARNING: $cmd not found in PATH. sync-and-index.sh will search common locations at runtime."
    fi
done
echo ""

# --- Generate plist ---
cat > "$PLIST_FILE" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!--
  saas-mirror: periodic sync + index
  Generated by scheduling/setup.sh on $(date '+%Y-%m-%d %H:%M:%S')
  Repo: $MIRROR_DIR

  Runs every 30 minutes via sync-and-index.sh.
  Logs: /tmp/saas-mirror.log
  Status: launchctl list | grep saas-mirror
  Uninstall: scheduling/setup.sh uninstall
-->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$PLIST_NAME</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$MIRROR_DIR/scheduling/sync-and-index.sh</string>
    </array>
    <key>WorkingDirectory</key>
    <string>$MIRROR_DIR</string>
    <key>StartInterval</key>
    <integer>1800</integer>
    <key>StandardOutPath</key>
    <string>/tmp/saas-mirror.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/saas-mirror.log</string>
</dict>
</plist>
PLIST

echo "  Generated plist: $PLIST_FILE"

# --- Unload if already loaded ---
if launchctl list "$PLIST_NAME" &>/dev/null; then
    launchctl unload "$LINK_PATH" 2>/dev/null || true
    echo "  Unloaded previous service"
fi

# --- Symlink + load ---
mkdir -p "$AGENTS_DIR"
ln -sf "$PLIST_FILE" "$LINK_PATH"
echo "  Symlinked: $LINK_PATH -> $PLIST_FILE"

launchctl load "$LINK_PATH"
echo "  Loaded service"

# --- Summary ---
echo ""
echo "saas-mirror is now scheduled to sync every 30 minutes."
echo ""
echo "  Logs:      tail -f /tmp/saas-mirror.log"
echo "  Status:    launchctl list | grep saas-mirror"
echo "  Run now:   launchctl start $PLIST_NAME"
echo "  Uninstall: scheduling/setup.sh uninstall"
